# Translation in meter [m]
# Rotation in Quaternions

generated_at: '2024-03-28'
source_frame: pylon_camera
target_frame: base_link

# Ouster
rotation:
    qx: -0.50556569
    qy: 0.51272567
    qz: -0.48467689
    qw: 0.49659243
translation:
    x: -0.260
    y: 0.232874
    z: 0.548319
