# Translation in meter [m]
# Rotation in Quaternions

generated_at: '2023-05-30'
source_frame: os_lidar
target_frame: base_link


#Ouster rotation
rotation:
    qx: 0.0
    qy: 0.0
    qz: 1.0
    qw: 0.0

translation:
    x: -0.353768
    y: 0.0
    z: 0.73931
