repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        name: Trim trailing whitespaces
    -   id: end-of-file-fixer
        name: Add empty line to end of file
    -   id: check-yaml
        name: Validate YAML
    -   id: check-json
        name: Validate JSON
    -   id: check-xml
        name: Validate XML
    -   id: check-added-large-files
        name: Check large files (>500kB)
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
    -   id: clang-format
        name: Format C++ (clang-format)
        exclude: '.*\.m$'  # This line excludes MATLAB files
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        name: Format Python (black)
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: cpplint
        name: Static code analysis C++ (cpplint)
        exclude: '.*\.m$|^src/amzsim/amzsim_backend/amzsim_codegen_model'  # This line excludes MATLAB files and codegenerated model
