# --- Constraint parameters for the states

# Trackbound constraints (laterally from middle of the track)
trackbound_min: -1.5
trackbound_max: 1.5

# Constraints on longitudinal velocity (vx)
vx_max: 20.0
vx_max_terminal: 5.0

# Constraints on front and rear bicycle tire forces individually
axt_abs_max: 6.0
ayt_abs_max: 5.0

# Constraints on steering angle (dels)
dels_abs_max: 0.45

# --- Constraint parameters for the inputs

# Constraints on setpoint longitudinal acceleration rate (dax)
dax_min: -100.0
dax_max: 100.0

# Constraints on steering angle rate (ddels)
ddels_abs_max: 6.0
