# --- Cost function parameters

# enforce higher progress rate
q_ds: 0.1
q_ds_terminal: 0.0

# enforce less lateral deviation
q_n: 0.05
q_n_terminal: 12.0

# enforce less heading difference
q_mu: 0.5
q_mu_terminal: 7.0

# enforce less setpoint longitudinal acceleration rate
r_dax: 0.00001

# enforce less steering angle rate
r_ddels: 0.1

# --- Slack cost function parameters
slack_penalties:
  lin:
    S_te: 1.0  # tire ellipse
    S_vx: 0.2  # velocity
    S_tb: 0.5  # track boundaries
  quad:
    S_te: 5.0  # tire ellipse
    S_vx: 2.0  # velocity
    S_tb: 1.0  # track boundaries
