# vehicle mass
m: 200.0 # kg

# gravity
g: 9.81 # m/s^2

# distance from front axle to center of gravity
l_f: 0.78 # m

# distance from rear axle to center of gravity
l_r: 0.74 # m

# distance CoG to front of vehicle
l_to_front: 1.5 # m

# distance CoG to rear of vehicle
l_to_rear: 1.3 # m

# car width of the vehicle
car_width: 1.5 # m

# inertia around z-axis
Iz: 190.0 # kg*m^2

# height of center of gravity
h_cg: 0.2 # m

# drag coefficient 0.5 * a_front * rho * C_rd * vx^2
C_d: 1.55 # kg/m

# friction force coefficient
C_r: 0.12 # -

# lift coefficient 0.5 * a_front * rho * C_rl * vx^2
C_l: 3.4 # kg/m

# air density
rho: 1.225 # kg/m^3

# frontal area
A_front: 1.2 # m^2

# pacejka tire model parameters
B_tire: 10.0 # -
C_tire: 1.3 # -
D_tire: 1.0 # -

# standard reference curvature
kappa_ref: 0.0
