sensor_fusion:
  ros__parameters:
    debug:   false
    profiling_enabled: true

    topics:
      sub:
        points_compensated: "/perception/lidar_motion_compensator/compensated_pc"
        fw_bbox: "/perception/depth_estimation/bbox_depth"
        debug:
          fw_cam: "/forward_camera/pylon_ros2_camera_node/image_raw"
      pub:
        cone_array: "/perception/fusion/cone_array"
        debug:
          img_overlay: "/perception/sensor_fusion_baseline/debug/img_overlay"
          bbox_fusion: "/perception/sensor_fusion_baseline/debug/bbox_depth"
        runtime: "/perception/runtimes"

    # Image resolution
    image_width: 2592
    image_height: 352

    # Frame IDs
    frame_ids:
      camera: "pylon_camera"
      base_link: "base_link"
      reference_frame: "odom"

    # Camera intrinsics file
    intrinsics_file: "package://camera_launcher/config/calibration/forward_camera_CAR_NAME_2024.yaml"

    # Maximum offset between camera and compensated_lidar in ms (for ApproxSync)
    max_sync_offset: 150    # not used for now
    # Minimum time between subsequent camera/compensated_lidar messages (for ApproxSync)
    min_inter_message: 50  # # not used for now

    filter_tuning:
      # cone distances from the car taken into account
      min_cone_distance : 2.0 # (m)
      max_cone_distance: 30.0 # (m)
      # minimum accepted number of lidar points inside the filter area
      min_lidar_points: 3
      # skipping cones for which bounding box is close to the image bottom border
      image_bottom_border: 5 # (pixels)
      # filter the pointcloud near the bounding box by comparing the distance with depth estimation from camera
      max_dist_camera_depth : 1.5 # (m)
      # filter the pointcloud near the bounding box by comparing the image distance between lidar points and bounding box
      max_dist_pixels : 25.0 # (pixel)
      # distance offset for the averaging filter
      averaging_depth_offset: 1.0 # (m)
