# =========== General settings ===========
integrator_nodes_solver:    7

integrator_type:            'IRK4'
linear_solver:              'symm_indefinite' # Fastest solver : symm_indefinite_fast
solve_method:               'PDIP_NLP' # 'PDIP'(def) or 'ADMM' or 'DFG'

bfgs_init:                  0.1

n_runtime_param :           33
n_inputs:                   2
n_states:                   7
n_slacks:                   5

# Use printlevel = 2 to print progress (but not for timings)
print_level:                0
max_it:                     200

# max. number of threads to use in parallel
parallel:                   0

# 0: no optimization, 1: optimize for size, 2: optimize for speed, 3: optimize for size & speed
opt_level:                  3

overwrite:                  1  # 1: overwrite existing solver
server:                     'https://forces-6-3-0.embotech.com'
simulink:                   0
cleanup:                    0
#platform:                   'x86_64'
platform:                   'Gnu-x86_64'

# =========== Optimization settings ===========
hessian_approx:             'bfgs' # 'bfgs'(def) or 'gauss-newton'
# 1: check functions, 0: do not check functions (for deployment)
check_functions:            0
initialisation:             0 # Cold (0,def), Center(1), Warm(2)

mu_zero:                    1000000 # 1e6 default
accuracy_ineq:              0.00001 # (1e-6) residual for inequalities
accuracy_eq:                0.00001 # (1e-6) residual for equalities
accuracy_mu:                0.00001 # (1e-6) absolute duality gap
accuracy_rdgap:             0.0001 # (1e-5) relative duality gap := (pobj-dobj)/pobj

tol_stat:                   0.01 # stationarity (derivative equals zero)
tol_eq:                     0.01 # equality constraints
tol_ineq:                   0.01 # inequality constraints
tol_comp:                   0.01 # complementarity (slackness)

variable_elimination:       0
no_hash:                    1
integrator_sub_system:      0 # seems to be more stable and faster without
barr_strat:                 'loqo' #'loqo' (default) or to 'monotone'

sse:                        1

optimize_choleskydivision:  1
optimize_registers:         1
optimize_uselocalsall:      1
optimize_rearrange:         1
optimize_loopunrolling:     1
optimize_enableoffset:      1
