# Translation in meter [m]
# Rotation in Quaternions

generated_at: '2024-06-14'
source_frame: hesai_lidar
target_frame: base_link

#Hesai
rotation:
    qx: 0.0
    qy: 0.0
    qz: 1.0
    qw: 0.0

translation:
    x: -0.0338
    y: -0.0162
    z: 0.698
