cone_fusion:
  ros__parameters:
    debug: false
    profiling_enabled: true

    check_color_prob: true
    color_prob_thresh: 0.7  # Check if one color prob > x, if not, assign color prob to 0.25 for every class
    max_cone_error: 1.0 # in meters (m)
    max_set_size: 10
    wait_threshold: 200.0 # in ms

    topics:
      sub:
        camera_cone: "/perception/camera/cone_array"
        lidar_cone: "/perception/lidar/cone_array"
        sf_cone: "/perception/fusion/cone_array"
      pub:
        output_cone: "/perception/cone_array"
        runtime: "/perception/runtimes"

    post_processing:
      # Cone will be rejected if there is no neighbor within this distance
      min_distance_for_neighboring_cone_m: 6.5

      fused:
        # Max distance between car and cone
        min_cone_dist_from_car_m: 2.5
        # Max distance between car and cone
        max_cone_dist_from_car_m: 15.0
        # Field of view of the perception pipeline in degrees
        field_of_view_deg: 40.0

      lidar_only:
        # Max distance between car and cone
        min_cone_dist_from_car_m: 2.5
        # Max distance between car and cone
        max_cone_dist_from_car_m: 30.0
        # Field of view of the perception pipeline in degrees
        field_of_view_deg: 180.0

      camera_only:
        # Max distance between car and cone
        min_cone_dist_from_car_m: 2.5
        # Max distance between car and cone
        max_cone_dist_from_car_m: 10.0
        # Field of view of the perception pipeline in degrees
        field_of_view_deg: 120.0
