lidar_pipeline:
  ros__parameters:
    ouster:
      parameters:
        x_min: -35.0        # front
        x_max: 30.0         # rear
        y_min: -20.0        # left
        y_max: 20.0         # right
        z_min: -2.0         # down
        z_max: 0.5          # up
        x_min_car: -4.8     # front
        x_max_car: 2.0      # rear
        y_min_car: -1.0     # left
        y_max_car: 1.0      # right

        grid_num_x: 6
        grid_num_y: 6
        distance_treshold_for_ransac: 0.12
        min_point_in_segment: 50

        grid_filter_enabled: true
        rough_clustering_max_points_per_grid: 100
        rough_clustering_grid_size_m: 0.6

        rain: false

        cone_detection:
          enabled: true
          max_points_dbscan: 100
          max_cluster_z: 0.5
          min_cluster_std: 0.04
          zones:
            distance: [100.0]
            eps_dbscan_m: [1.0]
            min_points_dbscan: [2]
            std_threshold_orange: [0.105]
            max_cluster_std_dev: [0.2]

        pre_cluster:
          enabled: false
          max_points_dbscan: 100
          max_cluster_z: 0.5
          min_cluster_std: 0.04
          zones:
            distance: [100.0]
            eps_dbscan_m: [1.0]
            min_points_dbscan: [2]
            std_threshold_orange: [0.105]
            max_cluster_std_dev: [0.2]

      profiling:
        enabled: true

      logging:
        enabled: true

      visualization:
        enabled: true

      filter:
        enabled: false

      motion_compenation:
        enabled: true

      transform_cone:
        enabled: true

      debug:
        enabled: true

      topics:
        subscriber:
          topic_lidar_point: "/ouster/points"
        publisher:
          topic_cone_array: "/perception/lidar/cone_array"
          topic_compensated_pc: "/perception/lidar_motion_compensator/compensated_pc"
          topic_debug_filtered_pc: "/filtered_point_cloud"
          topic_debug_centroid_dbscan: "/cluster_centroids_markers"

      frame_id:
        fixed: "odom"
        cone_array: "base_link"

      ground_removal:
        max_iteration: 100

      downsampling:
        ratio: 1.0
        enabled: false
